[package]
name = "ipgrep"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive", "wrap_help"] }
git-version = "0"
memchr = "2"
ipnet = "2"

[dev-dependencies]
regex = "1"
